name       : libmikmod
version    : 3.3.10
release    : 2
source     :
    - http://netix.dl.sourceforge.net/project/mikmod/libmikmod/3.3.10/libmikmod-3.3.10.tar.gz : 00b3f5298431864ebd069de793ec969cfea3ae6f340f6dfae1ff7da1ae24ef48
license    :
    - LGPL-2.0
    - LGPL-2.1
component  : programming
summary    : libmikmod 3.3.8, a portable sound library for Unix and other systems.
description: |
    This is libmikmod, version 3.3.8, a portable sound library for Unix and other systems.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(libpulse)
    - pkgconfig(sdl)
    - pkgconfig(sdl2)
setup      : |
    %configure --enable-alsa --enable-sdl --disable-static
build      : |
    %make
install    : |
    %make_install
