name       : libmikmod
version    : 3.3.11.1
release    : 11
source     :
    - https://netix.dl.sourceforge.net/project/mikmod/libmikmod/3.3.11.1/libmikmod-3.3.11.1.tar.gz : ad9d64dfc8f83684876419ea7cd4ff4a41d8bcd8c23ef37ecb3a200a16b46d19
license    :
    - LGPL-2.0
    - LGPL-2.1
component  : programming.library
summary    : A portable sound library for Unix and other systems
description: |
    This is libmikmod, a portable sound library for Unix and other systems.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(libpulse)
    - pkgconfig(sdl)
    - pkgconfig(sdl2)
setup      : |
    %configure --enable-alsa --enable-sdl --disable-static
build      : |
    %make
install    : |
    %make_install
